### ISSUE TITLE
fix bug in execution of arena_game through start.py

### ISSUE THREAD

**Issue by phylyc** [arenarium/battleground_core#67]
scores remain 0 for all agents ?!?

**Comment by vincentropy** [comment]
It looks like the game ends after 1 move with all scores equal to 0.
The problem might be here:
https://github.com/vincentropy/battleground/blob/f29526831efd3d8a40bb3d18fabaf690a8c65019/battleground/game_runner.py#L23

where the game runner checks for game-over and gets a yes on the first round?

the game_over() method of ArenaGameEngine should return false on that line

**Comment by phylyc** [comment]
fixed.
